/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { ReportNotary, ReportNotaryInterface } from "../ReportNotary.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "reportId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "pdfHash",
        "type": "bytes32"
      }
    ],
    "name": "ReportHashStored",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "reportId",
        "type": "uint256"
      }
    ],
    "name": "getReportHash",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "reportId",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "pdfHash",
        "type": "bytes32"
      }
    ],
    "name": "storeReportHash",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600f57600080fd5b5061014e8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806336d266471461003b5780634d1f67391461006e575b600080fd5b61005b6100493660046100dd565b60009081526020819052604090205490565b6040519081526020015b60405180910390f35b61008161007c3660046100f6565b610091565b6040519015158152602001610065565b6000828152602081815260408083208490555183815284917f1554e7640be620fabb4d43ee81bb18960a94ca97040673c80e9886c9a50b98bd910160405180910390a250600192915050565b6000602082840312156100ef57600080fd5b5035919050565b6000806040838503121561010957600080fd5b5050803592602090910135915056fea26469706673582212209a9fb8995d07f6228c28bed04e6c06ceb5f2110b6dcdc5e48a87ae33d25cc4f664736f6c634300081c0033";

  
      type ReportNotaryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ReportNotaryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ReportNotary__factory extends ContractFactory {
    
      constructor(...args: ReportNotaryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<ReportNotary & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ReportNotary__factory {
      return super.connect(runner) as ReportNotary__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ReportNotaryInterface {
      return new Interface(_abi) as ReportNotaryInterface;
    }
    
    override attach(address: string | Addressable): ReportNotary {
      return super.attach(address) as ReportNotary;
    }
  static connect(address: string, runner?: ContractRunner | null): ReportNotary {
      return new Contract(address, _abi, runner) as unknown as ReportNotary;
    }
  }

  
  