/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ReportNotary', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReportNotary__factory>

  getContractAt(name: 'ReportNotary', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReportNotary>

  deployContract(name: 'ReportNotary', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReportNotary>

  deployContract(name: 'ReportNotary', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReportNotary>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  