/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ReportNotaryInterface extends Interface {
    getFunction(nameOrSignature: "getReportHash" | "storeReportHash"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ReportHashStored"): EventFragment;

    encodeFunctionData(functionFragment: 'getReportHash', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'storeReportHash', values: [BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getReportHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeReportHash', data: BytesLike): Result;
  }

  
    export namespace ReportHashStoredEvent {
      export type InputTuple = [reportId: BigNumberish, pdfHash: BytesLike];
      export type OutputTuple = [reportId: bigint, pdfHash: string];
      export interface OutputObject {reportId: bigint, pdfHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReportNotary extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReportNotary;
    waitForDeployment(): Promise<this>;

    interface: ReportNotaryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getReportHash: TypedContractMethod<
      [reportId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    storeReportHash: TypedContractMethod<
      [reportId: BigNumberish, pdfHash: BytesLike, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getReportHash'): TypedContractMethod<
      [reportId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'storeReportHash'): TypedContractMethod<
      [reportId: BigNumberish, pdfHash: BytesLike, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'ReportHashStored'): TypedContractEvent<ReportHashStoredEvent.InputTuple, ReportHashStoredEvent.OutputTuple, ReportHashStoredEvent.OutputObject>;

    filters: {
      
      'ReportHashStored(uint256,bytes32)': TypedContractEvent<ReportHashStoredEvent.InputTuple, ReportHashStoredEvent.OutputTuple, ReportHashStoredEvent.OutputObject>;
      ReportHashStored: TypedContractEvent<ReportHashStoredEvent.InputTuple, ReportHashStoredEvent.OutputTuple, ReportHashStoredEvent.OutputObject>;
    
    };
  }